board:
    build: .
    volumes:
        - .:/sb
nginx:
    image: nginx:latest
    ports:
        - "8000:8000"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
        - board
    links:
        - board
